COINS_FA = {
    "btc": "BTCUSDT", "bitcoin": "BTCUSDT", "بیتکوین": "BTCUSDT", "بیت کوین": "BTCUSDT", "بیت": "BTCUSDT",
    "eth": "ETHUSDT", "ethereum": "ETHUSDT", "اتریوم": "ETHUSDT",
    "bnb": "BNBUSDT", "binance": "BNBUSDT", "بایننس": "BNBUSDT", "بایننس کوین": "BNBUSDT",
    "sol": "SOLUSDT", "solana": "SOLUSDT", "سولانا": "SOLUSDT",
    "xrp": "XRPUSDT", "ripple": "XRPUSDT", "ریپل": "XRPUSDT",
    "doge": "DOGEUSDT", "dogecoin": "DOGEUSDT", "دوج": "DOGEUSDT", "دوج کوین": "DOGEUSDT",
    "ada": "ADAUSDT", "cardano": "ADAUSDT", "کاردانو": "ADAUSDT",
    "avax": "AVAXUSDT", "avalanche": "AVAXUSDT", "آوالانچ": "AVAXUSDT",
    "link": "LINKUSDT", "chainlink": "LINKUSDT", "چین لینک": "LINKUSDT", "چینلینک": "LINKUSDT",
    "dot": "DOTUSDT", "polkadot": "DOTUSDT", "پولکادات": "DOTUSDT",
    "ltc": "LTCUSDT", "litecoin": "LTCUSDT", "لایت کوین": "LTCUSDT", "لایتکوین": "LTCUSDT",
    "bch": "BCHUSDT", "bitcoin cash": "BCHUSDT", "بیتکوین کش": "BCHUSDT",
    "trx": "TRXUSDT", "tron": "TRXUSDT", "ترون": "TRXUSDT",
    "ton": "TONUSDT", "toncoin": "TONUSDT", "تون": "TONUSDT", "تون کوین": "TONUSDT",
    "sui": "SUIUSDT", "سویی": "SUIUSDT",
    "apt": "APTUSDT", "aptos": "APTUSDT", "اپتوس": "APTUSDT",
    "arb": "ARBUSDT", "arbitrum": "ARBUSDT", "آربیتروم": "ARBUSDT",
    "op": "OPUSDT", "optimism": "OPUSDT", "اپتیمیسم": "OPUSDT",
    "near": "NEARUSDT", "نیر": "NEARUSDT",
    "atom": "ATOMUSDT", "cosmos": "ATOMUSDT", "کازموس": "ATOMUSDT", "اتم": "ATOMUSDT",
    "inj": "INJUSDT", "injective": "INJUSDT", "اینجکتیو": "INJUSDT",
    "tia": "TIAUSDT", "celestia": "TIAUSDT", "سلستیا": "TIAUSDT",
    "fil": "FILUSDT", "filecoin": "FILUSDT", "فایل کوین": "FILUSDT",
    "icp": "ICPUSDT", "internet computer": "ICPUSDT", "اینترنت کامپیوتر": "ICPUSDT",
    "hbar": "HBARUSDT", "hedera": "HBARUSDT", "هدرا": "HBARUSDT",
    "etc": "ETCUSDT", "ethereum classic": "ETCUSDT", "اتریوم کلاسیک": "ETCUSDT",
    "uni": "UNIUSDT", "uniswap": "UNIUSDT", "یونی": "UNIUSDT", "یونی سواپ": "UNIUSDT",
    "aave": "AAVEUSDT", "آوه": "AAVEUSDT",
    "pepe": "PEPEUSDT", "پپه": "PEPEUSDT",
    "shib": "SHIBUSDT", "shiba": "SHIBUSDT", "شیبا": "SHIBUSDT",
    "wif": "WIFUSDT", "dogwifhat": "WIFUSDT", "ویف": "WIFUSDT",
    "bonk": "BONKUSDT", "بونک": "BONKUSDT",
    "floki": "FLOKIUSDT", "فلوکی": "FLOKIUSDT",
    "not": "NOTUSDT", "notcoin": "NOTUSDT", "نات": "NOTUSDT", "نات کوین": "NOTUSDT",
    "jup": "JUPUSDT", "jupiter": "JUPUSDT", "ژوپیتر": "JUPUSDT",
    "sei": "SEIUSDT", "سی": "SEIUSDT",
    "stx": "STXUSDT", "stacks": "STXUSDT", "استکس": "STXUSDT",
    "pendle": "PENDLEUSDT", "پندل": "PENDLEUSDT",
    "render": "RENDERUSDT", "rndr": "RENDERUSDT", "رندر": "RENDERUSDT",
    "fet": "FETUSDT", "fetch": "FETUSDT", "فچ": "FETUSDT",
    "gala": "GALAUSDT", "گالا": "GALAUSDT",
    "sand": "SANDUSDT", "sandbox": "SANDUSDT", "سند": "SANDUSDT",
    "mana": "MANAUSDT", "decentraland": "MANAUSDT", "مانا": "MANAUSDT",
    "axs": "AXSUSDT", "axie": "AXSUSDT", "اکسی": "AXSUSDT",
    "gmt": "GMTUSDT", "جی ام تی": "GMTUSDT",
    "ape": "APEUSDT", "apecoin": "APEUSDT", "ایپ": "APEUSDT",
    "blur": "BLURUSDT", "بلر": "BLURUSDT",
    "ens": "ENSUSDT", "ای ان اس": "ENSUSDT",
    "lido": "LDOUSDT", "ldo": "LDOUSDT", "لیدو": "LDOUSDT",
    "crv": "CRVUSDT", "curve": "CRVUSDT", "کرو": "CRVUSDT",
    "sushi": "SUSHIUSDT", "سوشی": "SUSHIUSDT",
    "comp": "COMPUSDT", "compound": "COMPUSDT", "کامپاند": "COMPUSDT",
    "mkr": "MKRUSDT", "maker": "MKRUSDT", "میکر": "MKRUSDT",
    "snx": "SNXUSDT", "synthetix": "SNXUSDT", "سینتتیکس": "SNXUSDT",
    "yfi": "YFIUSDT", "yearn": "YFIUSDT", "یرن": "YFIUSDT",
    "cake": "CAKEUSDT", "pancake": "CAKEUSDT", "کیک": "CAKEUSDT",
    "1inch": "1INCHUSDT", "وان اینچ": "1INCHUSDT",
    "rune": "RUNEUSDT", "thorchain": "RUNEUSDT", "رون": "RUNEUSDT",
    "kava": "KAVAUSDT", "کاوا": "KAVAUSDT",
    "zil": "ZILUSDT", "zilliqa": "ZILUSDT", "زیلیکا": "ZILUSDT",
    "qtum": "QTUMUSDT", "کوانتوم": "QTUMUSDT",
    "iota": "IOTAUSDT", "آیوتا": "IOTAUSDT",
    "eos": "EOSUSDT", "ایاس": "EOSUSDT",
    "neo": "NEOUSDT", "نئو": "NEOUSDT",
    "zec": "ZECUSDT", "zcash": "ZECUSDT", "زی کش": "ZECUSDT",
    "dash": "DASHUSDT", "دش": "DASHUSDT",
    "xmr": "XMRUSDT", "monero": "XMRUSDT", "مونرو": "XMRUSDT",
    "xem": "XEMUSDT", "نم": "XEMUSDT",
    "waves": "WAVESUSDT", "ویوز": "WAVESUSDT",
    "one": "ONEUSDT", "harmony": "ONEUSDT", "هارمونی": "ONEUSDT",
    "hot": "HOTUSDT", "holo": "HOTUSDT", "هولو": "HOTUSDT",
    "ankr": "ANKRUSDT", "انکر": "ANKRUSDT",
    "chz": "CHZUSDT", "chiliz": "CHZUSDT", "چیلیز": "CHZUSDT",
    "bat": "BATUSDT", "basic attention": "BATUSDT", "بت": "BATUSDT",
    "zrx": "ZRXUSDT", "زیرو ایکس": "ZRXUSDT",
    "ont": "ONTUSDT", "ontology": "ONTUSDT", "آنتولوژی": "ONTUSDT",
    "rvn": "RVNUSDT", "ravencoin": "RVNUSDT", "ریون": "RVNUSDT",
    "celr": "CELRUSDT", "celer": "CELRUSDT", "سلر": "CELRUSDT",
    "ctsi": "CTSIUSDT", "cartesi": "CTSIUSDT", "کارتزی": "CTSIUSDT",
    "skl": "SKLUSDT", "skale": "SKLUSDT", "اسکیل": "SKLUSDT",
    "alpha": "ALPHAUSDT", "آلفا": "ALPHAUSDT",
    "audio": "AUDIOUSDT", "آدیو": "AUDIOUSDT",
    "people": "PEOPLEUSDT", "پیپل": "PEOPLEUSDT",
    "lrc": "LRCUSDT", "loopring": "LRCUSDT", "لوپرینگ": "LRCUSDT",
    "mask": "MASKUSDT", "مسک": "MASKUSDT",
    "rose": "ROSEUSDT", "oasis": "ROSEUSDT", "رز": "ROSEUSDT",
    "ocean": "OCEANUSDT", "اوشن": "OCEANUSDT",
    "band": "BANDUSDT", "بند": "BANDUSDT",
    "api3": "API3USDT", "ای پی آی 3": "API3USDT",
    "coti": "COTIUSDT", "کوتی": "COTIUSDT",
    "iotx": "IOTXUSDT", "آیوتکس": "IOTXUSDT",
    "lpt": "LPTUSDT", "livepeer": "LPTUSDT", "لایوپیر": "LPTUSDT",
    "mina": "MINAUSDT", "مینا": "MINAUSDT",
    "flow": "FLOWUSDT", "فلو": "FLOWUSDT",
    "ksm": "KSMUSDT", "kusama": "KSMUSDT", "کوساما": "KSMUSDT",
    "glmr": "GLMRUSDT", "moonbeam": "GLMRUSDT", "مون بیم": "GLMRUSDT",
    "imx": "IMXUSDT", "immutable": "IMXUSDT", "ایموتبل": "IMXUSDT",
    "gmx": "GMXUSDT", "جی ام ایکس": "GMXUSDT",
    "dydx": "DYDXUSDT", "دی وای دی ایکس": "DYDXUSDT",
    "magic": "MAGICUSDT", "مجیک": "MAGICUSDT",
    "id": "IDUSDT", "space id": "IDUSDT", "اسپیس آی دی": "IDUSDT",
    "hook": "HOOKUSDT", "هوک": "HOOKUSDT",
    "high": "HIGHUSDT", "های": "HIGHUSDT",
    "edu": "EDUUSDT", "ادو": "EDUUSDT",
    "cyber": "CYBERUSDT", "سایبر": "CYBERUSDT",
    "arkm": "ARKMUSDT", "arkham": "ARKMUSDT", "آرکهام": "ARKMUSDT",
    "wld": "WLDUSDT", "worldcoin": "WLDUSDT", "ورلد کوین": "WLDUSDT",
    "manta": "MANTAUSDT", "مانتا": "MANTAUSDT",
    "strk": "STRKUSDT", "starknet": "STRKUSDT", "استارک نت": "STRKUSDT",
    "pyth": "PYTHUSDT", "پایت": "PYTHUSDT",
    "dym": "DYMUSDT", "dymension": "DYMUSDT", "دایمنشن": "DYMUSDT",
    "alt": "ALTUSDT", "altlayer": "ALTUSDT", "آلت لیر": "ALTUSDT",
    "ace": "ACEUSDT", "ایس": "ACEUSDT",
    "nfp": "NFPUSDT", "ان اف پی": "NFPUSDT",
    "ai": "AIUSDT", "sleepless ai": "AIUSDT", "ای آی": "AIUSDT",
    "xai": "XAIUSDT", "ایکس ای آی": "XAIUSDT",
    "meme": "MEMEUSDT", "میم": "MEMEUSDT",
    "ordi": "ORDIUSDT", "اوردی": "ORDIUSDT",
    "sats": "1000SATSUSDT", "1000sats": "1000SATSUSDT", "ساتس": "1000SATSUSDT",
    "rats": "RATSUSDT", "رتس": "RATSUSDT",
    "tao": "TAOUSDT", "bittensor": "TAOUSDT", "تائو": "TAOUSDT",
    "beam": "BEAMXUSDT", "beamx": "BEAMXUSDT", "بیم": "BEAMXUSDT",
    "kas": "KASUSDT", "kaspa": "KASUSDT", "کسپا": "KASUSDT",
    "ftm": "FTMUSDT", "fantom": "FTMUSDT", "فانتوم": "FTMUSDT",
    "vet": "VETUSDT", "vechain": "VETUSDT", "وی چین": "VETUSDT",
    "algo": "ALGOUSDT", "algorand": "ALGOUSDT", "الگورند": "ALGOUSDT",
    "egld": "EGLDUSDT", "multiversx": "EGLDUSDT", "الروند": "EGLDUSDT",
    "xtz": "XTZUSDT", "tezos": "XTZUSDT", "تزوس": "XTZUSDT",
    "theta": "THETAUSDT", "تتا": "THETAUSDT",
    "grt": "GRTUSDT", "graph": "GRTUSDT", "گراف": "GRTUSDT",
    "qnt": "QNTUSDT", "quant": "QNTUSDT", "کوانت": "QNTUSDT",
    "enj": "ENJUSDT", "enjin": "ENJUSDT", "انجین": "ENJUSDT",
    "ach": "ACHUSDT", "alchemy pay": "ACHUSDT", "الکمی": "ACHUSDT",
    "rlc": "RLCUSDT", "آر ال سی": "RLCUSDT",
    "storj": "STORJUSDT", "استورج": "STORJUSDT",
    "waxp": "WAXPUSDT", "واکس": "WAXPUSDT",
    "sxp": "SXPUSDT", "سایپ": "SXPUSDT",
    "omg": "OMGUSDT", "او ام جی": "OMGUSDT",
    "dent": "DENTUSDT", "دنت": "DENTUSDT",
    "reef": "REEFUSDT", "ریف": "REEFUSDT",
    "jasmy": "JASMYUSDT", "جاسمی": "JASMYUSDT",
    "gmt": "GMTUSDT", "stepn": "GMTUSDT", "استپن": "GMTUSDT",
}
