from __future__ import annotations
import os
TELEGRAM_BOT_TOKEN=os.getenv('TELEGRAM_BOT_TOKEN','')
TELEGRAM_CHAT_ID=os.getenv('TELEGRAM_CHAT_ID','')
TELEGRAM_POLL_SECONDS=1.0
OKX_BASE_URL=os.getenv('OKX_BASE_URL','https://www.okx.com')
OKX_REQUEST_TIMEOUT=8
OKX_BAR='5m'; OKX_CONTEXT_BAR='15m'; OKX_TRIGGER_BAR='1m'; OKX_CANDLE_LIMIT=300
OKX_MICRO_TRADES_LIMIT=100; OKX_BOOK_DEPTH=5; OKX_MICRO_WINDOW_SECONDS=10; OKX_MICRO_MIN_TRADES=8
USE_CONFIRMED_CANDLES_ONLY=True
TOOBIT_BASE_URL=os.getenv('TOOBIT_BASE_URL','https://api.toobit.com')
TOOBIT_API_KEY=os.getenv('TOOBIT_API_KEY','')
TOOBIT_API_SECRET=os.getenv('TOOBIT_API_SECRET',os.getenv('TOOBIT_SECRET_KEY',''))
REQUEST_TIMEOUT=8; RECV_WINDOW=5000
TOOBIT_FUTURES_PATH_EXCHANGE_INFO=os.getenv('TOOBIT_FUTURES_PATH_EXCHANGE_INFO','/api/v1/futures/exchangeInfo')
TOOBIT_FUTURES_PATH_BALANCE=os.getenv('TOOBIT_FUTURES_PATH_BALANCE','/api/v1/futures/balance')
TOOBIT_FUTURES_PATH_ORDER=os.getenv('TOOBIT_FUTURES_PATH_ORDER','/api/v1/futures/order')
TOOBIT_FUTURES_PATH_POSITIONS=os.getenv('TOOBIT_FUTURES_PATH_POSITIONS','/api/v1/futures/position')
TOOBIT_FUTURES_PATH_LEVERAGE=os.getenv('TOOBIT_FUTURES_PATH_LEVERAGE','/api/v1/futures/leverage')
TOOBIT_FUTURES_PATH_MARGIN_TYPE=os.getenv('TOOBIT_FUTURES_PATH_MARGIN_TYPE','/api/v1/futures/marginType')
TOOBIT_FUTURES_PATH_ORDER_HISTORY=os.getenv('TOOBIT_FUTURES_PATH_ORDER_HISTORY','/api/v1/futures/historyOrders')
TRADING_ENABLED_DEFAULT=False; AUTO_SIGNAL_ENABLED_DEFAULT=True
TRADE_USDT_DEFAULT=10.0; TRADE_USDT_MIN=1.0; TRADE_USDT_MAX=10000.0
LEVERAGE_DEFAULT=10; LEVERAGE_MIN=1; LEVERAGE_MAX=100
MAX_POSITIONS_DEFAULT=3; MAX_POSITIONS_MIN=1; MAX_POSITIONS_MAX=100
ISOLATED_MARGIN_REQUIRED=True; ORDER_OPEN_CHECK_SECONDS=70; REAL_PENDING_TIMEOUT_SECONDS=120
TOOBIT_FUTURES_MAKER_FEE_PCT=0.02; TOOBIT_FUTURES_TAKER_FEE_PCT=0.05
TOOBIT_REALIZED_PNL_INCLUDES_FEES=os.getenv('TOOBIT_REALIZED_PNL_INCLUDES_FEES','false').lower() in ('1','true','yes')
ENTRY_SLIPPAGE_PCT=0.03; TP_SLIPPAGE_PCT=0.02; SL_SLIPPAGE_PCT=0.05
MIN_NET_RR_ABSOLUTE=1.20; TARGET_NET_RR=1.35; STRONG_NET_RR=1.50
MIN_NET_PROFIT_USDT=0.05; MIN_NET_RETURN_ON_MARGIN_PCT=1.50
MIN_SL_PCT=0.35; NORMAL_MAX_SL_PCT=1.00; ADAPTIVE_MAX_SL_PCT=1.20
ATR_PERIOD=14; EMA_FAST=9; EMA_MID=21; EMA_SLOW=50; RSI_PERIOD=14; ADX_PERIOD=14
DIRECTION_MIN=68.0; STRENGTH_MIN=60.0; FRESHNESS_MIN=64.0; SETUP_MIN=75.0; TRIGGER_MIN=74.0; SAFETY_MIN=65.0; FINAL_MIN=74.0
WATCH_TTL_SECONDS=30*60; WATCH_POLL_INTERVAL_SECONDS=5.0; SCAN_INTERVAL_SECONDS=60.0
SETUP_WATCH_MIN=65.0; WATCH_LATE_LIMIT_ATR=0.65; SIGNAL_PUBLISH_RETRY_COOLDOWN_SECONDS=300
EXECUTION_MAX_DEVIATION_PCT=0.25; EXECUTION_MAX_DEVIATION_SL_FRACTION=0.35; MIN_FREE_MARGIN_BUFFER_PCT=5.0
SIGNAL_COOLDOWN_SECONDS_PER_SYMBOL=20*60; VIRTUAL_MONITOR_MAX_MINUTES=240; RESULT_RETRY_BASE_SECONDS=30; RESULT_RETRY_MAX_SECONDS=1800
DB_PATH=os.getenv('BOT_DB_PATH','bot_state.sqlite3'); LOG_LEVEL=os.getenv('BOT_LOG_LEVEL','INFO')
LEARNING_MIN_SAMPLES=40; SHADOW_MIN_SAMPLES=30; SHADOW_MIN_DAYS=7; LEARNING_INTERVAL_SECONDS=3600
