"""تنظیمات نهایی ربات UEM یک‌ساعته."""
from __future__ import annotations
import os

# Telegram
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
TELEGRAM_POLL_SECONDS = 1.0

# OKX public market data
OKX_BASE_URL = os.getenv("OKX_BASE_URL", "https://www.okx.com")
OKX_REQUEST_TIMEOUT = 8
OKX_PRIMARY_BAR = "1H"
OKX_MONITOR_BAR = "5m"
OKX_CANDLE_LIMIT = 180
OKX_MICRO_TRADES_LIMIT = 200
OKX_BOOK_DEPTH = 20

# Toobit Futures - مسیرها با فایل ثابت سازگارند
TOOBIT_BASE_URL = os.getenv("TOOBIT_BASE_URL", "https://api.toobit.com")
TOOBIT_API_KEY = os.getenv("TOOBIT_API_KEY", "")
TOOBIT_API_SECRET = os.getenv("TOOBIT_API_SECRET", os.getenv("TOOBIT_SECRET_KEY", ""))
REQUEST_TIMEOUT = 8
RECV_WINDOW = 5000
TOOBIT_FUTURES_PATH_EXCHANGE_INFO = os.getenv("TOOBIT_FUTURES_PATH_EXCHANGE_INFO", "/api/v1/futures/exchangeInfo")
TOOBIT_FUTURES_PATH_BALANCE = os.getenv("TOOBIT_FUTURES_PATH_BALANCE", "/api/v1/futures/balance")
TOOBIT_FUTURES_PATH_ORDER = os.getenv("TOOBIT_FUTURES_PATH_ORDER", "/api/v1/futures/order")
TOOBIT_FUTURES_PATH_POSITIONS = os.getenv("TOOBIT_FUTURES_PATH_POSITIONS", "/api/v1/futures/position")
TOOBIT_FUTURES_PATH_LEVERAGE = os.getenv("TOOBIT_FUTURES_PATH_LEVERAGE", "/api/v1/futures/leverage")
TOOBIT_FUTURES_PATH_MARGIN_TYPE = os.getenv("TOOBIT_FUTURES_PATH_MARGIN_TYPE", "/api/v1/futures/marginType")
TOOBIT_FUTURES_PATH_ORDER_HISTORY = os.getenv("TOOBIT_FUTURES_PATH_ORDER_HISTORY", "/api/v1/futures/historyOrders")

# User controls
TRADING_ENABLED_DEFAULT = False
AUTO_SIGNAL_ENABLED_DEFAULT = True
TRADE_USDT_DEFAULT = 10.0
TRADE_USDT_MIN = 1.0
TRADE_USDT_MAX = 10000.0
LEVERAGE_DEFAULT = 10
LEVERAGE_MIN = 1
LEVERAGE_MAX = 100
MAX_POSITIONS_DEFAULT = 3
MAX_POSITIONS_MIN = 1
MAX_POSITIONS_MAX = 200
ISOLATED_MARGIN_REQUIRED = True
ORDER_OPEN_CHECK_SECONDS = 70

# Risk / fees
RISK_REWARD = 1.5
MIN_NET_PROFIT_USDT = 0.10
MIN_NET_PROFIT_SAFETY_USDT = 0.05
MAKER_FEE_PCT_PER_SIDE = 0.02
TAKER_FEE_PCT_PER_SIDE = 0.05
SLIPPAGE_PCT_PER_SIDE = 0.02
ENTRY_FEE_MODE = "TAKER"
EXIT_FEE_MODE = "TAKER"
TP_FORECAST_FRACTION = 0.88
SL_SAFETY_MIN_PCT = 10.0
SL_SAFETY_NORMAL_PCT = 18.0
SL_SAFETY_HIGH_PCT = 28.0
MIN_STOP_ATR_MULTIPLIER = 0.60
MAX_STOP_ATR_MULTIPLIER = 1.35

# Engine cadence
LIGHT_SCAN_INTERVAL_SECONDS = 60
WATCH_INTERVAL_SECONDS = 3
WATCH_MAX_SECONDS = 30 * 60
MONITOR_INTERVAL_SECONDS = 20
VIRTUAL_MONITOR_RECENT_LIMIT = 300
VIRTUAL_MONITOR_1H_AFTER_HOURS = 20
TOOBIT_STATUS_INTERVAL_SECONDS = 15
SIGNAL_COOLDOWN_SECONDS_PER_SYMBOL = 25 * 60
SYMBOL_ERROR_BLACKLIST_SECONDS = 30 * 60
MAX_WATCH_SYMBOLS = 8

# Market quality gates
MAX_SPREAD_PCT = 0.12
MIN_ABS_TRADE_IMBALANCE = 0.10
MIN_ABS_BOOK_IMBALANCE = 0.08
MICROPRICE_MIN_BIAS_PCT = 0.004
MAX_ENTRY_CHASE_ATR = 0.45

# Storage / logs
DB_PATH = os.getenv("BOT_DB_PATH", "bot_state.sqlite3")
LOG_LEVEL = os.getenv("BOT_LOG_LEVEL", "INFO")
LOG_REJECT_REASONS = True
REJECT_LOG_REPEAT_SECONDS = 30

# Adaptive watch / pump-dump detection
WATCH_REANALYZE_SECONDS = 15
WATCH_HISTORY_SIZE = 12
WATCH_OPPOSITE_CONFIRMATIONS = 2
WATCH_ALIGNED_CONFIRMATIONS = 2
WATCH_INVALIDATION_ATR_BUFFER = 0.12
WATCH_REVERSAL_MOVE_ATR = 0.28
IMPULSE_BAR = "5m"
IMPULSE_CANDLE_LIMIT = 80
IMPULSE_LOOKBACK_BARS = 6
IMPULSE_MIN_MOVE_ATR = 0.35
IMPULSE_MIN_MOVE_PCT = 0.22
IMPULSE_MIN_VOLUME_RATIO = 1.15
IMPULSE_MIN_DIRECTIONAL_BARS = 4
IMPULSE_ENTRY_RETRACE_ATR = 0.20
